CREATE TABLE businesses (id BIGSERIAL PRIMARY KEY,name VARCHAR(200) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE app_users (id BIGSERIAL PRIMARY KEY,business_id BIGINT NOT NULL REFERENCES businesses(id),email VARCHAR(255) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role VARCHAR(50) NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE customers (id BIGSERIAL PRIMARY KEY,business_id BIGINT NOT NULL REFERENCES businesses(id),name VARCHAR(200) NOT NULL,email VARCHAR(255),phone VARCHAR(50),gstin VARCHAR(30),status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_customers_business_id ON customers(business_id);
